<?php if (!empty($this->getMessages())): ?>
<div class="alert alert-danger" role="alert">
    <?php foreach ($this->getMessages() as $key => $message): ?>
        <div><?= array_shift($message) ?></div>
    <?php endforeach; ?>
    <?php endif; ?>
<div class="d-flex justify-content-center align-items-center vh-40">
    <div class="position-relative">
        <div class="position-absolute top-40 start-40 translate-middle">
            <h1>Login page</h1>

            <form style="min-width: 300px" action="/account/login" method="post">
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email"
                           class="form-control"
                           id="exampleInputEmail1"
                           aria-describedby="emailHelp"
                           placeholder="Enter email"
                           name="email">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password"
                           class="form-control"
                           id="exampleInputPassword1"
                           placeholder="Password"
                           name="password">
                </div>
                <div class="form-group">
                    <label for="singup">If you dont have acc yet</label>
                    <span id="singup">
                        <a href="/account/register">SingUp</a>
                    </span>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>