<div class="">
    <div class="">
        <div class="">
            <form class="col-lg-5 offset-lg-3 " style="min-width: 200px" action="/account/login" method="post">
                <div class="form-group row justify-content-center">
                    <h3>Login</h3>
                </div>
                <div class="form-group row justify-content-center">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email"
                           class="form-control"
                           id="exampleInputEmail1"
                           aria-describedby="emailHelp"
                           placeholder="Enter email"
                           name="email">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
                <div class="form-group row justify-content-center">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password"
                           class="form-control"
                           id="exampleInputPassword1"
                           placeholder="Password"
                           name="password">
                </div>
                <div class="form-group row justify-content-center">
                    <span>If you dont have acc yet: </span>
                    <span style ='margin-left: 5px' id="singup">
                        <a href="/account/register">SingUp</a>
                    </span>
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>
</div>