<div class="d-flex justify-content-center align-items-center vh-40">
    <div class="position-relative">
        <div class="position-absolute top-40 start-40 translate-middle">
            <h1>Register page</h1>

            <form style="min-width: 300px" id="register" action="/account/register" method="post">
                <div class="form-group">
                    <label for="exampleInputUsername1">Username</label>
                    <input type="text" name="username" class="form-control" id="exampleInputUsername1" placeholder="Username">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                </div>
                <select name="role" id="role" form="register">
                    <option value="user">User</option>
                    <option value="admin">Admin</option>
                </select>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
