<?php
$items = $this->getData('items');
?>

<h1>List view</h1>
<a style="max-width: 300px" class="btn btn-primary" href="/vehicle/create" role="button">Create</a>
<?php if ($items && !empty($items)): ?>
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Vehicle Type</th>
        <th scope="col">Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($items as $item): ?>
    <tr>
        <th scope="row"><?= $item->getId(); ?></th>
        <td><?= $item->getName(); ?></td>
        <td>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle"
                        type="button"
                        id="dropdownMenuButton<?= $item->getId(); ?>"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Action
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="/vehicle/<?= $item->getId(); ?>">View</a>
                    <a class="dropdown-item" href="/vehicle/edit/<?= $item->getId(); ?>">Edit</a>
                    <a id="<?= $item->getId();?>"
                       class="dropdown-item delete"
                       method="delete"
                       href="/vehicle/delete/<?= $item->getId(); ?>">
                        Delete
                    </a>
                </div>
            </div>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
    <p>No items</p>
<?php endif; ?>
<script>
    $(document).ready(function() {
        $('.dropdown-item.delete').click(function(e) {
            e.preventDefault();
            var itemId = $(this).attr('id');
            var confirmation = confirm('Are you sure you want to delete this item?');

            if (confirmation) {
                $.ajax({
                    url: '/vehicle/delete/' + itemId,
                    type: 'DELETE',
                    success: function(response) {
                        location.reload();
                        console.log('Item deleted successfully');

                    },
                    error: function(xhr, status, error) {
                        console.error('Error deleting item:', error);
                    }
                });
            }
        });
    });
</script>
